<div class="row">
    <div class="col-md">
        <h1>Setup parsing parameters</h1>
        <form action="/parse/start" method="post">
            <div class="form-group">
                <label for="url">Site URL:</label>
                <input type="url" class="form-control" id="url" name="url" placeholder="http://site.example.com">
            </div>
            <div class="form-group">
                <label for="lavel">Parse lavel:</label>
                <input type="number" class="form-control" id="lavel" name="lavel" value="0">
            </div>
            <div class="form-group">
                <label for="lavel">Email count:</label>
                <input type="number" class="form-control" id="lavel" name="max_count" value="1">
            </div>
            <button type="submit" class="btn btn-primary">Start</button>
        </form>
    </div>
</div>